### ISSUE TITLE
sgminer-gm v5.5.5-4 - starts but loses stratum and never accepts

### ISSUE THREAD

**Issue by scavern** [nicehash/sgminer-gm#3]
sgminer-gm v5.5.5-4 - starts but loses stratum and never accepts when mining on nicehash pool.

This is on ubuntu 14.04. I have tested sgminer-gm with another pool and it mines correctly.

**Comment by kenshirothefist** [comment]
Did you take a look at https://github.com/nicehash/sgminer-gm/releases/download/5.5.5-4/sgminer-gm_startup_scripts.zip ?

**Comment by scavern** [comment]
Yes I did. Still no success.

**Comment by kenshirothefist** [comment]
You might want to try the latest version. Also, please post your full command line that you use to start the miner and also let us know what kind of GPUs are you trying to use.

**Comment by scavern** [comment]
Doesn't matter now, rigs are being converted to Windows.

________________________________
